### ISSUE TITLE
Joint supports a list of possible topologies and they are checked in auto-joint

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#151]
https://miro.com/app/board/uXjVN5YAx98=/

![Image](https://github.com/gramaziokohler/compas_timber/assets/3398309/571daf5c-f276-483f-b901-0d4f388ae097)

**Comment by chenkasirer** [comment]
@obucklin @fgramazio @mhelmrei @jonashaldemann tried to sketch joints and the topologies they could be applied to. Some are obviously native to a certain topology but given the user knows what they're doing could be applied to other topologies. Feel free to comment.

**Comment by jonashaldemann** [comment]
- Maybe it makes sense to generalise the Joints that can have multiple Topologies, instead of Having T-Butt and L-Butt with L/T/X to merge them to one "Butt" that reacts to the different Topologies.
- HalfLap could also have the L-Topology 
![image](https://github.com/gramaziokohler/compas_timber/assets/104436733/7d6aabc6-c661-4855-b8dd-fe5e88ad9133)

**Comment by chenkasirer** [comment]
we moved more towards 1:1 relationship between topology and joint (e.g T_TOPO <-> THalfLap) so this is essentially not needed.
