### ISSUE TITLE
Make a `SimpleSequenceGenerator` for `compas.datastructure.Assembly`

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#191]
`AssemblySequenceGenerator`

**Comment by chenkasirer** [comment]
@jckenny59 even though it wouldn't be super elegant, we could also just allow caller to pass in an Assembly and then in case it's a `TimberAssembly` assign Steps to `assembly.beams` and otherwise to `assembly.parts()`.

```python 
if isinstance(assembly, TimberAssembly):
    parts = assembly.beams
else:
    parts = assembly.parts()

for part in parts:
    # add part to building plan
```

**Comment by jckenny59** [comment]
@chenkasirer Very true this would for sure be an option. I am fine either way and can do it however you prefer. This way would be an even easier implementation on my side, because then I don't have to care if it is an Assembly or TimberAssembly... But I think if we want to move the `AssemblySequenceGenerator` out of Timbers sometime, then it also makes sense to do it separately. I can do either way, whichever you prefer!

**Comment by chenkasirer** [comment]
@jckenny59 for sake of documentation and future reference: we agreed to do it the way of checking the type for now, so no new class.
